import {generatePDF} from 'react-native-html-to-pdf';
import Share from 'react-native-share';
import dayjs from 'dayjs';
import {Gym} from '../types';
import {COLORS} from '../constants';

interface InvoiceLineItem {
  label: string;
  amount: number;
}

interface InvoiceData {
  invoiceNo: string;
  date: string;
  title: string;
  payerName: string;
  payerPhone?: string | null;
  items: InvoiceLineItem[];
  total: number;
  method: string;
  note?: string | null;
}

const escapeHtml = (str: string): string =>
  str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const formatINR = (amount: number): string =>
  `Rs. ${Number(amount).toLocaleString('en-IN', {minimumFractionDigits: 2, maximumFractionDigits: 2})}`;

function buildInvoiceHtml(gym: Gym, data: InvoiceData): string {
  const rows = data.items
    .map(
      item => `
        <tr>
          <td style="padding:10px;border-bottom:1px solid #eee;">${escapeHtml(item.label)}</td>
          <td style="padding:10px;border-bottom:1px solid #eee;text-align:right;">${formatINR(item.amount)}</td>
        </tr>`,
    )
    .join('');

  return `
  <html>
    <head><meta charset="utf-8" /></head>
    <body style="font-family:Helvetica,Arial,sans-serif;color:#1A1A2E;padding:24px;">
      <div style="border-bottom:3px solid ${COLORS.primary};padding-bottom:16px;margin-bottom:24px;display:flex;justify-content:space-between;">
        <div>
          <h1 style="margin:0;color:${COLORS.primary};font-size:22px;">${escapeHtml(gym.gym_name)}</h1>
          <p style="margin:4px 0 0;font-size:12px;color:#6B7280;">${escapeHtml(gym.address || '')}</p>
          <p style="margin:2px 0 0;font-size:12px;color:#6B7280;">${escapeHtml(gym.phone || '')} ${gym.email ? '· ' + escapeHtml(gym.email) : ''}</p>
        </div>
        <div style="text-align:right;">
          <h2 style="margin:0;font-size:18px;">${escapeHtml(data.title)}</h2>
          <p style="margin:4px 0 0;font-size:12px;color:#6B7280;">Invoice #${escapeHtml(data.invoiceNo)}</p>
          <p style="margin:2px 0 0;font-size:12px;color:#6B7280;">${dayjs(data.date).format('DD MMM YYYY')}</p>
        </div>
      </div>

      <table style="width:100%;border-collapse:collapse;margin-bottom:16px;">
        <tr>
          <td style="padding:4px 0;font-size:12px;color:#6B7280;">Billed To</td>
          <td style="padding:4px 0;font-size:12px;color:#6B7280;text-align:right;">Payment Method</td>
        </tr>
        <tr>
          <td style="padding:0;font-size:15px;font-weight:bold;">${escapeHtml(data.payerName)}</td>
          <td style="padding:0;font-size:15px;font-weight:bold;text-align:right;">${escapeHtml(data.method)}</td>
        </tr>
        ${data.payerPhone ? `<tr><td colspan="2" style="padding:2px 0;font-size:12px;color:#6B7280;">${escapeHtml(data.payerPhone)}</td></tr>` : ''}
      </table>

      <table style="width:100%;border-collapse:collapse;">
        <thead>
          <tr style="background:${COLORS.primary}15;">
            <th style="padding:10px;text-align:left;font-size:12px;color:${COLORS.primary};">Description</th>
            <th style="padding:10px;text-align:right;font-size:12px;color:${COLORS.primary};">Amount</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
        <tfoot>
          <tr>
            <td style="padding:14px 10px;font-size:15px;font-weight:bold;">Total</td>
            <td style="padding:14px 10px;font-size:15px;font-weight:bold;text-align:right;color:${COLORS.primary};">${formatINR(data.total)}</td>
          </tr>
        </tfoot>
      </table>

      ${data.note ? `<p style="margin-top:20px;font-size:12px;color:#6B7280;">Note: ${escapeHtml(data.note)}</p>` : ''}

      <p style="margin-top:32px;font-size:11px;color:#9CA3AF;text-align:center;">
        Generated by Gymblix · ${dayjs().format('DD MMM YYYY, HH:mm')}
      </p>
    </body>
  </html>`;
}

export async function shareInvoice(gym: Gym, data: InvoiceData): Promise<void> {
  const html = buildInvoiceHtml(gym, data);
  const pdf = await generatePDF({
    html,
    fileName: `Invoice_${data.invoiceNo}`,
    base64: false,
  });

  if (!pdf.filePath) {
    throw new Error('Failed to generate invoice PDF');
  }

  const filePath = pdf.filePath.startsWith('file://') ? pdf.filePath : `file://${pdf.filePath}`;

  await Share.open({
    url: filePath,
    type: 'application/pdf',
    title: 'Share Invoice',
    failOnCancel: false,
  });
}

export type {InvoiceData, InvoiceLineItem};
